// <auto-generated />
using System;
using CampusShuttleAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusShuttleAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240927224244_registershuttle")]
    partial class registershuttle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusShuttleAPI.Model.RegisterShuttle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShuttleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShuttleId");

                    b.HasIndex("UserId");

                    b.ToTable("RegisterShuttles");
                });

            modelBuilder.Entity("CampusShuttleAPI.Model.Shuttle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Shuttles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new DateTime(2024, 9, 28, 1, 42, 44, 338, DateTimeKind.Local).AddTicks(9215),
                            Destination = "Sandton Gautrain Station"
                        },
                        new
                        {
                            Id = 2,
                            DepartureTime = new DateTime(2024, 9, 28, 2, 42, 44, 338, DateTimeKind.Local).AddTicks(9239),
                            Destination = "Varsity College Sandton"
                        });
                });

            modelBuilder.Entity("CampusShuttleAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            Password = "password1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            Password = "password2"
                        });
                });

            modelBuilder.Entity("CampusShuttleAPI.Model.RegisterShuttle", b =>
                {
                    b.HasOne("CampusShuttleAPI.Model.Shuttle", "Shuttle")
                        .WithMany()
                        .HasForeignKey("ShuttleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusShuttleAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shuttle");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
